# Generated by Django 4.2.3 on 2023-07-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.employee_master'),
        ),
    ]
